volumes:
  db-setup:

services:
  db:
    image: postgres:alpine3.20
    volumes:
      - db-setup:/postgres_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: islamic-centre
  